version: '2'
services:
  wscef:
    image: farribeiro/wscef-docker
    build: .
    devices:
      - /dev/snd:/dev/snd
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/home/ff/.Xauthority
      - HOST_HOSTNAME=${HOSTNAME}
    cpuset: '0'
    mem_limit: 512M
    network_mode: host
    volumes:
      - /dev/shm:/dev/shm
      - ${XAUTHORITY}:/tmp/.docker.xauth:ro
      - ~/BankFiles:/home/ff/Downloads
